apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: dtolmach/go-app:latest
        ports:
        - containerPort: 8080
        workingDir: /app
        command: [ "./go-app" ]