user: ENC[AES256_GCM,data:TGpx/ds=,iv:PG6JoL1kmDG6dlZwFLZ6C3folIzUN+ba/NGZ0h/agWw=,tag:zpqnJ5WtCXMnrsdnYRlbpg==,type:str]
password: ENC[AES256_GCM,data:KWswow2Cr8/ZvWI=,iv:Sy+GA6GeVTLtthZn9OEXUrR6SGFZFFnYEhRaj7wczWY=,tag:2UpQ4F06cu9NLZ20oN9TsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-06T13:18:59Z"
    mac: ENC[AES256_GCM,data:ils+bn8ZVqiLjkOXu4X4Wdb4Z470hp6zAOIuE16d4gcVc5IFz3M2deW0B1aY8Zi/8YTqrEIBrT4Y8Tyw/J97qguEWvSprKdB+So5sVGXGKPVfs5pUM6IujeDpX3D8Ivt2+XOc+Xew7GgPKMBUZ+49BJSwu9goKal/X2xhZNRPsk=,iv:JUOZo2w5fwbQxkG9EMNrSjl/XUSGsL8mzs8nDOESd4w=,tag:OAg0aPedHrL0iTBWxlhjqw==,type:str]
    pgp:
        - created_at: "2025-03-06T13:17:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA37YDQZFWsQKAQwAlv2C/ruuhYp3GJiVU9FIZ3gf8MPGjbq0YFRDlZ7sE0Fv
            AqIpTGGT7YMnNMAd781hmwBJv0i2nrMXKnpz5PDMt/YLYPG73m0gNe8BPMYkNBO0
            UwhH2iqzVvjvd/OV0im92e4vl2NBH0MJaNIoG+QkXUdLX4+z1nvyY2Cl+TzdVHIx
            mZJEzHm/fVyurbNS3UtdOp7kwitFNmWuvc6nTjW8GzNJXSDZRpdJvzNeG41bv7zq
            VoF2u6xhnvOygDlDZegofG+cTZvqSYS6J/QDkM9lcR5/vcWySU6lhfxfCN3FICE5
            gsA0zCTbKPGAorCjfGgppMUh5+EHcuabd2SAlUSy1JAHg/IrBvVx5FNSYSxs/pYT
            MKl3xCXOJi9PREZ19S1n+wh8VvJKhevsDs6N6ec5dGKaDaZjH1eDsog+hazQPKyH
            vFocRNEGjI1Odc4In3QgJaow2oQxdTKa+53pP6CYDg6LWu5mRdE1svrlz2k7pZii
            Et30LKbCbqMn0AakK7vZ0l4BjC6BECRU6J8TXoVvvULzGaOGPC4h6CqmXXSUGGZX
            XRu9LzbGLk/V13reYFbbfCbiPKFFgt+OQ1Q7KzGjEKEb4MATrPffd6Yq6GH2yczo
            DAAwJCq5MfQzB/ilQEJb
            =yAqO
            -----END PGP MESSAGE-----
          fp: E7F5A8B6AE82781025D3CED919E567A932941FD0
    unencrypted_suffix: _unencrypted
    version: 3.7.3
