name: Python CI

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/python_app_ci.yml'
  pull_request:
    paths:
    - 'app_python/**'
    - '.github/workflows/python_app_ci.yml'

jobs:
  build-test:
    name: Build, test, lint
    defaults:
      run:
        working-directory: app_python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: app_python/requirements.txt

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Run Linter
        run: flake8 main.py test_app.py

      - name: Run Unit Tests
        run: pytest test_app.py

  security:
    needs: [build-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --skip-unresolved app_python/

  docker:
    name: Docker Build&Push
    defaults:
      run:
        working-directory: app_python
    needs: [build-test, security]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-app:latest
